# Use ubuntu 14.04 instead of 12.04 because we need the newer version of libc6 to run
# make4.
sudo: required
dist: trusty

# According to https://docs.travis-ci.com/user/ci-environment/#Runtimes,
# a go compiler is always present in an environment. Since Travis CI only support
# one language, we use C.
language: c

matrix:
    include:
        - compiler: gcc-4.7
        - compiler: gcc-5

before_install:
    - sudo apt-get update

install:
    # TODO: to remove when GNU make >= 4.0 in travis CI
    - wget http://ftp.us.debian.org/debian/pool/main/m/make-dfsg/make_4.0-8.1_amd64.deb
    - sudo dpkg -i make_4.0-8.1_amd64.deb

script:
    # Build everything and test with go1.2
    - eval "$(gimme 1.2)" && make all check
    # Test with go1.4
    - rm out/pythia && rm -r go/pkg go/bin && eval "$(gimme 1.4)" && make go check
    # Test with go1.6
    - rm out/pythia && rm -r go/pkg go/bin && eval "$(gimme 1.6)" && make go check
    # Test with go1.7
    - rm out/pythia && rm -r go/pkg go/bin && eval "$(gimme 1.7)" && make go check
    # Test with go1.8
    - rm out/pythia && rm -r go/pkg go/bin && eval "$(gimme 1.8)" && make go check

addons:
    apt:
        sources:
            ubuntu-toolchain-r-test
        packages:
            - kernel-package
            - libncurses5-dev
            - fakeroot
            - wget
            - bzip2
            - squashfs-tools
            - gcc-4.7
            - gcc-4.7-multilib
            - gcc-5
            - gcc-5-multilib
            - gcc-multilib
